apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: sandbox-node
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sandbox-node
        tier: frontend
    spec:
      containers:
      - name: node-app
        image: "tomyogms/tmf_sample_app:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
    app: sandbox-node
    tier: frontend
spec:
  type: NodePort
  selector:
    app: sandbox-node
    tier: frontend
  ports:
  - port: 3000  
    targetPort: 3000
    protocol: TCP
    name: node-app-port
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb-sandbox
  labels:
    app: sandbox-node
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sandbox-node
        tier: backend
    spec:
      containers:
      - name: mongo
        image: "mongo:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: sandbox-node
    tier: backend
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: sandobox-mongodb-port
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mqtt-sandbox
  labels:
    app: sandbox-node
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sandbox-node
        tier: backend
    spec:
      containers:
      - name: mongo
        image: "ncarlier/mqtt:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 31798
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: sandbox-node
    tier: backend
  ports:
  - port: 31798
    targetPort: 31798
    protocol: TCP
    name: sandobox-mqtt-port